import { Footer } from '#/components/footer'
import { Nav } from '#/components/nav'
import '#/styles/globals.css'
import { Space_Grotesk, Poppins } from 'next/font/google'

const grotesk = Space_Grotesk({ subsets: ['latin'], weight: ['400', '600'], variable: "--font" })
const poppins = Poppins({ subsets: ['latin'], weight: ['200', '400', '600', '800'], variable: "--font-title" })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${grotesk.variable} ${poppins.variable}`}>
      <body>
        <main>
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}